default_platform :android

platform :android do
    before_all do
        ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    end

    ######################### PUBLIC LANES #########################

    desc "Deploy a new Dev APK to #converge-codelab-qa channel"
    lane :dev do |options|
        build(
            flavor: "Dev"
        )
        upload_to_slack()
    end


    ######################### PRIVATE LANES #########################

    desc "Build a new APK"
    private_lane :build do |options|
        gradle(
            task: "clean assemble",
            build_type: "Release"
        )
    end

    desc "Upload the latest output APK to #converge-codelab-QA Slack channel"
    private_lane :upload_to_slack do |options|
        full_file_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
        file_name = full_file_path.gsub(/\/.*\//,"")
        sh "echo Uploading " + file_name + " to #converge-codelab-QA Slack"
        sh "curl https://slack.com/api/files.upload -F token=\"xoxp-424384161762-444215239027-444219583828-f17f17abf2312ef367c3c3f528d7cdc1\" -F channels=\"converge-codelab-qa\" -F title=\"" + file_name + "\" -F filename=\"" + file_name + "\" -F file=@" + full_file_path
    end

    ######################### UTILS #########################

    ######################### POST #########################

    after_all do |lane|
        file_name = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH].gsub(/\/.*\//,"")
        slack(
            message: "Kampala Java Developers Successfully deployed App !:",
            default_payloads: [
                :git_branch,
                :last_git_commit_hash,
                :last_git_commit_message
            ],
            payload: {
                # Optional, lets you specify any number of your own Slack attachments.
                "Build Date" => Time.new.to_s,
                "APK" => file_name
            },
            success: true
        )
    end
end
